name: 'teams-chat-notification'
description: 'Teams Chat Notification for GitHub Actions'
author: 'agungsdas'
inputs:
  name:
    description: 'job name.'
    required: true
  url:
    description: 'teams chat webhook url.'
    required: true
  status:
    description: 'job status.'
    required: true
  testflight:
    description: 'testflight link.'
    required: false
  firebase:
    description: 'firebase link.'
    required: false
  register-firebase:
    description: 'firebase registration link.'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'bell'
  color: 'green'
